# Generated by Django 5.0 on 2023-12-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.IntegerField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
